Add shell settings

diff --git a/shell/bash_prompt b/shell/bash_prompt
--- a/shell/bash_prompt
+++ b/shell/bash_prompt
@@ -1,125 +1,215 @@
 #!/usr/bin/env bash
+# https://github.com/alrra/dotfiles/blob/master/src/shell/bash_prompt
 
-# https://github.com/mathiasbynens/dotfiles/blob/master/.bash_prompt
-# Shell prompt based on the Solarized Dark theme.
-# Screenshot: http://i.imgur.com/EkEtphC.png
-# Heavily inspired by @necolas’s prompt: https://github.com/necolas/dotfiles
-# iTerm → Profiles → Text → use 13pt Monaco with 1.1 vertical spacing.
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
-	export TERM='gnome-256color';
-elif infocmp xterm-256color >/dev/null 2>&1; then
-	export TERM='xterm-256color';
-fi;
+enable_color_support() {
 
-source ~/.aliases
+    if [[ $COLORTERM == gnome-* && $TERM == xterm ]] \
+        && infocmp gnome-256color &> /dev/null; then
+        export TERM="gnome-256color"
+    elif infocmp xterm-256color &> /dev/null; then
+        export TERM="xterm-256color"
+    fi
 
-prompt_git() {
-	local s='';
-	local branchName='';
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-	# Check if the current directory is in a Git repository.
-	if [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ]; then
+    # Load OS specific color support.
 
-		# check if the current directory is in .git before running git checks
-		if [ "$(git rev-parse --is-inside-git-dir 2> /dev/null)" == 'false' ]; then
+    . "colors/$OS/bash_colors"
 
-			# Ensure the index is up to date.
-			git update-index --really-refresh -q &>/dev/null;
-
-			# Check for uncommitted changes in the index.
-			if ! $(git diff --quiet --ignore-submodules --cached); then
-				s+='+';
-			fi;
-
-			# Check for unstaged changes.
-			if ! $(git diff-files --quiet --ignore-submodules --); then
-				s+='!';
-			fi;
-
-			# Check for untracked files.
-			if [ -n "$(git ls-files --others --exclude-standard)" ]; then
-				s+='?';
-			fi;
-
-			# Check for stashed files.
-			if $(git rev-parse --verify refs/stash &>/dev/null); then
-				s+='$';
-			fi;
-
-		fi;
-
-		# Get the short symbolic ref.
-		# If HEAD isn’t a symbolic ref, get the short SHA for the latest commit
-		# Otherwise, just give up.
-		branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
-			git rev-parse --short HEAD 2> /dev/null || \
-			echo '(unknown)')";
-
-		[ -n "${s}" ] && s=" [${s}]";
-
-		echo -e "${1}${branchName}${2}${s}";
-	else
-		return;
-	fi;
 }
 
-if tput setaf 1 &> /dev/null; then
-	tput sgr0; # reset colors
-	bold=$(tput bold);
-	reset=$(tput sgr0);
-	# Solarized colors, taken from http://git.io/solarized-colors.
-	black=$(tput setaf 0);
-	blue=$(tput setaf 33);
-	cyan=$(tput setaf 37);
-	green=$(tput setaf 64);
-	orange=$(tput setaf 166);
-	purple=$(tput setaf 125);
-	red=$(tput setaf 124);
-	violet=$(tput setaf 61);
-	white=$(tput setaf 15);
-	yellow=$(tput setaf 136);
-else
-	bold='';
-	reset="\e[0m";
-	black="\e[1;30m";
-	blue="\e[1;34m";
-	cyan="\e[1;36m";
-	green="\e[1;32m";
-	orange="\e[1;33m";
-	purple="\e[1;35m";
-	red="\e[1;31m";
-	violet="\e[1;35m";
-	white="\e[1;37m";
-	yellow="\e[1;33m";
-fi;
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-# Highlight the user name when logged in as root.
-if [[ "${USER}" == "root" ]]; then
-	userStyle="${red}";
-else
-	userStyle="${orange}";
-fi;
+# [!] Don't break this function into smaller, more specialized ones
+# as you will only pollute the global space even more. This function
+# cannot be unset because it's called every time the prompt string
+# is shown.
 
-# Highlight the hostname when connected via SSH.
-if [[ "${SSH_TTY}" ]]; then
-	hostStyle="${bold}${red}";
-else
-	hostStyle="${yellow}";
-fi;
+get_git_repository_details() {
 
-# Set the terminal title and prompt.
-PS1="\[\033]0;\W\007\]"; # working directory base name
-PS1+="\[${bold}\]\n"; # newline
-PS1+="\[${userStyle}\]\u"; # username
-PS1+="\[${white}\] at ";
-PS1+="\[${hostStyle}\]\h"; # host
-PS1+="\[${white}\] in ";
-PS1+="\[${green}\]\w"; # working directory full path
-PS1+="\$(prompt_git \"\[${white}\] on \[${violet}\]\" \"\[${blue}\]\")"; # Git repository details
-PS1+="\n";
-PS1+="\[${white}\]\$ \[${reset}\]"; # `$` (and reset color)
-export PS1;
+    local branchName=""
+    local tmp=""
 
-PS2="\[${yellow}\]→ \[${reset}\]";
-export PS2;
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    # Check if the current directory is in a Git repository.
+
+    ! git rev-parse &>/dev/null \
+        && return
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    # Check if in `.git/` directory (some of the following
+    # checks don't make sense/won't work in the `.git` directory).
+
+    [ "$(git rev-parse --is-inside-git-dir)" == "true" ] \
+        && return
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    # Check for uncommitted changes in the index.
+
+    if ! git diff --quiet --ignore-submodules --cached; then
+        tmp="$tmp+";
+    fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    # Check for unstaged changes.
+
+    if ! git diff-files --quiet --ignore-submodules --; then
+        tmp="$tmp!";
+    fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    # Check for untracked files.
+
+    if [ -n "$(git ls-files --others --exclude-standard)" ]; then
+        tmp="$tmp?";
+    fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    # Check for stashed files.
+
+    if git rev-parse --verify refs/stash &>/dev/null; then
+        tmp="$tmp$";
+    fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    [ -n "$tmp" ] \
+        && tmp=" [$tmp]"
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    branchName="$( printf "%s" "$( git rev-parse --abbrev-ref HEAD 2> /dev/null \
+        || git rev-parse --short HEAD 2> /dev/null \
+        || printf " (unknown)" )" | tr -d "\n" )"
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    printf "%s" "$1$branchName$tmp"
+
+}
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+set_prompts() {
+
+    local bold=$(tput bold 2> /dev/null)
+    local reset=$(tput sgr0 2> /dev/null)
+
+    local cyan=""
+    local green=""
+    local orange=""
+    local white=""
+    local yellow=""
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    if [ "$(tput colors 2> /dev/null || printf "0")" -ge 256 ]; then
+
+        # Solarized colors.
+        # https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values
+
+        cyan=$(tput setaf 37)
+        green=$(tput setaf 64)
+        orange=$(tput setaf 166)
+        white=$(tput setaf 15)
+        yellow=$(tput setaf 136)
+
+    fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    # Prompt Statement variables.
+    # http://ss64.com/bash/syntax-prompt.html
+
+    # ------------------------------------------------------------------
+    # | PS1 - Default interactive prompt                               |
+    # ------------------------------------------------------------------
+
+    PS1="\[\033]0;\W\007\]" # Terminal title (set to the
+                            # current working directory)
+
+    PS1+="$reset$bold"
+    PS1+="$orange\u"        # Username
+    PS1+="$white@"
+    PS1+="$yellow\h"        # Host
+    PS1+="$white: "
+    PS1+="$green\w"         # Working directory
+    PS1+="\$(get_git_repository_details \"$white on $cyan\")"
+    PS1+="\n"
+    PS1+="\[$reset\]\[$white\]$ \[$reset\]"
+
+    export PS1
+
+    # ------------------------------------------------------------------
+    # | PS2 - Continuation interactive prompt                          |
+    # ------------------------------------------------------------------
+
+    PS2="⚡ "
+
+    export PS2
+
+    # ------------------------------------------------------------------
+    # | PS4 - Debug prompt                                             |
+    # ------------------------------------------------------------------
+
+    # e.g:
+    #
+    # The GNU `date` command has the `%N` interpreted sequence while
+    # other implementations don't (on macOS `gdate` can be used instead
+    # of the native `date` if the `coreutils` package has been installed).
+    #
+    # local dateCmd=""
+    #
+    # if [ "$(date +%N)" != "N" ] || \
+    #    [ ! -x "$(command -v "gdate")" ]; then
+    #    dateCmd="date +%s.%N"
+    # else
+    #    dateCmd="gdate +%s.%N"
+    # fi
+    #
+    # PS4="+$( tput cr && tput cuf 6 &&
+    #          printf "$yellow %s $green%6s $reset" "$($dateCmd)" "[$LINENO]" )"
+    #
+    # PS4 output:
+    #
+    #   ++    1357074705.875970000  [123] '[' 1 == 0 ']'
+    #   └──┬─┘└────┬───┘ └───┬───┘ └──┬─┘ └──────┬─────┘
+    #      │       │         │        │          │
+    #      │       │         │        │          └─ command
+    #      │       │         │        └─ line number
+    #      │       │         └─ nanoseconds
+    #      │       └─ seconds since 1970-01-01 00:00:00 UTC
+    #      └─ depth-level of the subshell
+
+    PS4="+$( tput cr 2> /dev/null;
+             tput cuf 6 2> /dev/null;
+             printf "%s" "$reset" )"
+
+    export PS4
+
+}
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+main() {
+    enable_color_support
+    set_prompts
+}
+
+main
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+# Cleanup.
+
+unset -f enable_color_support
+unset -f main
+unset -f set_prompts
